#!/bin/bash

# Installation code.

if [[ "${1}" == "go" ]]; then
	ECHO=
	shift
else
	ECHO=echo
fi

DEST="${1}"
if [[ -z "${DEST}" ]]; then
	echo "*** please supply the home-assistant /config directory"
	exit 1
fi	
if [[ ! -d "${DEST}" ]]; then
	echo "*** please make sure the destination directory ${DEST} exists"
	exit 1
fi

if [[ -n "${ECHO}" ]]; then
	echo "**** would run the following commands, use './install go $1' to do the work"
fi

echo -- installing
${ECHO} mkdir -p "${DEST}/www"
${ECHO} cp -afv dist/hass-aarlo.js "${DEST}/www/aarlo-glance.js"
echo -- finished at "$(date '+%A at %H:%M:%S')"

